language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ti3rn1210/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ti3rn1210/react-test npm test

after_success:
  - docker build -t ti3rn1210/multi-client ./client
  - docker build -t ti3rn1210/multi-nginx ./nginx
  - docker build -t ti3rn1210/multi-server ./server
  - docker build -t ti3rn1210/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ti3rn1210/multi-client
  - docker push ti3rn1210/multi-nginx
  - docker push ti3rn1210/multi-server
  - docker push ti3rn1210/multi-worker